#!/bin/bash

#Bee bootstrap script. You typically invoke this script directly. It's responsible for
#downloading a dotnet runtime if required, and for downloading a bee distribution if required, and for starting the actual bee
#driver executable.
set -euo pipefail

#these two values will be replaced by the buildprocess when this script is used in a bootstrap distribution. When not replaced
#this script assumes it lives next to the standalone driver
use_bee_from_steve="bee/b81bb0b1ec56_675bdaa3af73d772d4fa0fea36db50f08015e7a629e86c5617d74c938bb0695f.zip"
use_bee_from_steve_repo="https://public-stevedore.unity3d.com/r/public"

if [[ "$use_bee_from_steve_repo" =~ .*testing.* ]]; then
  echo "Warning this bee bootstrap script is using a bee from the testing repository. This fine for testing, but not to use in production."
fi

if [[ "$OSTYPE" == "msys" ]]; then
  echo "It looks like you're running the bee bash script on windows. This is not supported, run bee.bat or bee.ps1 instead"
  exit 1
fi

#stevedore artifacts for the dotnet runtimes. these are produced by the yamato CI for our "netcorerun" repo. The zip file contains
#an info file that describes from which git commit / yamato-id it was built.  They are plain upstream packages, just unzipped & rezipped
#with this extra information added.
dotnet_runtime_linux="dotnet-runtime-linux-x64/966cbdc_06ea0fd0c2b630692f01ac852886cb0c102f585e6202f31757721496e9cc07c9.zip" #net-runtime 6.0.3
dotnet_runtime_osx_x64="dotnet-runtime-osx-x64/966cbdc_1040c0b7364ba17ab2d73815d549747e730c2ca235d8ff1ca9921dec4706271e.zip" #net-runtime 6.0.3
dotnet_runtime_osx_arm64="dotnet-runtime-osx-arm64/966cbdc_8f43f199553806d77fcb453095b5ef6172f5814714729e0def392d27f1137f3c.zip" #net-runtime 6.0.3

steve_artifact_return_value=""

download_or_return_steve_artifact()
{
    local steve_name="$1"

    #we could extend this to parse the Stevedore.conf, and to attempt downloads from multiple mirrors
    local steve_repo_url="$2"
    local unzip_dir_path="$HOME/.beebootstrap/$steve_name"

    if [ ! -d "$unzip_dir_path" ]; then
        if [ "$(which curl)" = /snap/bin/curl ]
        then
            echo "WARNING: apparmor can interfere with the curl snap package."
            echo "If you get access denied errors, install curl normally:"
            echo "  sudo apt-get install -y curl"
            sleep 1
        fi

        echo "Downloading $3."

        download_link="$steve_repo_url/$steve_name"
        temporary_dir="$HOME/.beebootstrap/download_$RANDOM"
        mkdir -p "$temporary_dir"
        downloaded_file="$temporary_dir/download.zip"

        #--fail means that if the http result is not OK, curl will actually fail. if not it will write a beautiful 404 page into $downloaded_file and exit with code 0
        curl --fail  --location "$download_link" --output "$downloaded_file"

        #after downloading into the temporary directory, we unzip it into the same temporary directory
        unzip -q -d "$temporary_dir" "$downloaded_file"
        #then we delete the zip file, so only its contents remain
        rm -f "$downloaded_file"

        #we ensure the directory we need to put the final result in's parent directory exist.
        mkdir -p "$(dirname "$unzip_dir_path")"

        #and we move the temporary directory to the final location. We use a move, so that it's atomic, and a failed download, or a failed unzp cannot
        #result in a situation where the targetdirectory did get created, but did not get properly populated. This way we can use the presence of the directory
        #as indication
        mv "$temporary_dir" "$unzip_dir_path"
    fi

    #bash does not support return values, so we assign it to a global. yep.
    steve_artifact_return_value="$unzip_dir_path"
}

dotnet_runtime_steve=""
determine_dotnet_runtime_steve() {
   type="$(uname)-$(uname -m)"
   case "$type" in
       Darwin-x86_64)
           dotnet_runtime_steve="$dotnet_runtime_osx_x64"
           ;;
       Darwin-arm64)
           dotnet_runtime_steve="$dotnet_runtime_osx_arm64"
           ;;
       Linux-x86_64)
           dotnet_runtime_steve="$dotnet_runtime_linux"
           ;;
       *)
           echo "Unsupported system: $type"
           exit 1
           ;;
   esac
}

if [ "$use_bee_from_steve" == "no" ]; then
    #this script supports running as part of a full bee distribution. In this case, use_bee_from_steve is not set,
    #and we find the path to the distribution by looking at where the script itself is. It shuold be placed in Standalone/Release of the distribution
    standalone_release="$(dirname "$0")"
else
    #we also support downloading the bee distribution from a stevedore server. In this case use_bee_from_steve should be set to a stevedore artifact name.
    #we'll download it and run it. In this mode, the only thing a user needs to version in their repo is this script.
    download_or_return_steve_artifact "$use_bee_from_steve" "$use_bee_from_steve_repo" "Bee distribution"
    standalone_release="$steve_artifact_return_value/Standalone/Release"
fi

distribution_path="$(cd "${standalone_release}/../.." && pwd)"
standalone_path="$standalone_release/Bee.StandaloneDriver.exe"
if [ ! -e "$standalone_path" ]; then
    standalone_path="$standalone_release/Bee.StandaloneDriver.dll"
fi


determine_dotnet_runtime_steve
download_or_return_steve_artifact "$dotnet_runtime_steve" "https://public-stevedore.unity3d.com/r/public" "Dotnet runtime"
dotnet_exe="$steve_artifact_return_value/dotnet"

#we assign BEE_DOTNET_MUXER env var here, so that the bee that is running knows how it can use this dotnet runtime to start other net5 framework dependent apps.
#it uses this to run the stevedore downloader program on net5.
export BEE_DOTNET_MUXER="$dotnet_exe"
export BEE_DISTRIBUTION_PATH="$distribution_path"

"$dotnet_exe" "$standalone_path" "$@"
